### ISSUE TITLE
bears start moving early

### ISSUE THREAD

**Issue by Thienanngvyen** [tmorris37/BeeHexed#8]
seems like bears already start moving towards the middle even though cards have not been played. After finally playing cards after the bears already have moved to the middle, the cards attack the bears in the middle but the game ended randomly (with hearts only at 75) instead of being at 0.

(Update) Read the readme and saw that this has to do with the final wave. I think alerting the player to know that this is the final wave or what wave they are on so they can adjust their strategy accordingly would be nice.

**Comment by korinX** [comment]
Fixed
